name: jobarchy_flutter_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  flutter_riverpod: ^3.0.3
  dio: ^5.3.0
  connectivity_plus: ^5.0.1
  fluttertoast: ^8.2.4
  shared_preferences: ^2.3.2
  cupertino_icons: ^1.0.8
  animate_do: ^3.0.2
  dropdown_button2: ^2.3.9
  google_fonts: ^6.1.0
  lottie: 3.3.1
  smooth_page_indicator: ^1.1.0
  font_awesome_flutter: ^10.7.0
  image_picker: ^1.2.0
  cached_network_image: ^3.3.1
  intl: ^0.19.0
  shimmer: ^3.0.0
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0


flutter:
  uses-material-design: true

  assets:
    - images/


  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italicc
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
 